/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.tomasz.stepien.formularzdaneosobowe;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tomme
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        addKeyListenerToHeightAndWeight();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLemail = new javax.swing.JLabel();
        jLlogin = new javax.swing.JLabel();
        Jldate = new javax.swing.JLabel();
        jLheight = new javax.swing.JLabel();
        jLweight = new javax.swing.JLabel();
        jTFlogin = new javax.swing.JTextField();
        jTFemail = new javax.swing.JTextField();
        jTFheight = new javax.swing.JTextField();
        jTFweight = new javax.swing.JTextField();
        jDCdate = new com.toedter.calendar.JDateChooser();
        jBsave = new javax.swing.JButton();
        jLform = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLemail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLemail.setText("Email:");

        jLlogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLlogin.setText("Login:");

        Jldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Jldate.setText("Data urodzenia:");

        jLheight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLheight.setText("Wzrost:");

        jLweight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLweight.setText("Waga:");

        jDCdate.setMaxSelectableDate(new java.util.Date(253370764899000L));

        jBsave.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBsave.setText("Zapisz");
        jBsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaveActionPerformed(evt);
            }
        });

        jLform.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLform.setText("Formularz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLweight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLheight, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jLemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Jldate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDCdate, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jTFweight)
                            .addComponent(jTFlogin)
                            .addComponent(jTFemail)
                            .addComponent(jTFheight)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLform, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLform, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLheight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFheight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLweight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFweight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDCdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jldate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBsave, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaveActionPerformed
        if(!checkEmail() == true){
        }else{
            String login = jTFlogin.getText();
            if(login.length() == 0){
                JOptionPane.showMessageDialog(null, "Podano nie poprawny Login!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String email = jTFemail.getText();
            String height = jTFheight.getText();
            if(height.length() == 0){
                JOptionPane.showMessageDialog(null, "Podano nie poprawny Wzrost!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                return;
            } 
            String weight = jTFweight.getText();
            if(weight.length() == 0){
                JOptionPane.showMessageDialog(null, "Podano nie poprawna Wage!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                return;
            } 
            String date = ""+jDCdate.getDate();
            if(jDCdate.getDate() == null){
                JOptionPane.showMessageDialog(null, "Podano nie poprawna Date!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                return;
            } 
            String file_name = "dane.txt";
            try {
                
                FileWriter fw = new FileWriter(new File(file_name),true);
                fw.write(login+";"+email+";"+height+";"+weight+";"+date+"\n");
                fw.close();
            } catch (IOException ex) {

            }
        }
        
    }//GEN-LAST:event_jBsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private void addKeyListenerToHeightAndWeight(){
        jTFheight.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                String height = jTFheight.getText();
                char ch = e.getKeyChar();
                if((ch >= '0' && ch <= '9' || ch == KeyEvent.VK_BACK_SPACE) && (height.length() < 3 || ch == KeyEvent.VK_BACK_SPACE)){
                    jTFheight.setEditable(true);
                    //jTADzisiejszeZakupy.setText(jTFCoKupiles.getText());
                } else {
                    jTFheight.setEditable(false);
                }
                
            }
            @Override
            public void keyPressed(KeyEvent e) {
            }
            @Override
            public void keyReleased(KeyEvent e) {  
            }
        });
        jTFweight.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                String weight = jTFweight.getText();
                char ch = e.getKeyChar();
                if((ch >= '0' && ch <= '9' || ch == KeyEvent.VK_BACK_SPACE) && (weight.length() < 3 || ch == KeyEvent.VK_BACK_SPACE)){
                    System.out.println(weight.length());
                    jTFweight.setEditable(true);
                    checkDate();
                    //jTADzisiejszeZakupy.setText(jTFCoKupiles.getText());
                } else {
                    jTFweight.setEditable(false);
                }
                
            }
            @Override
            public void keyPressed(KeyEvent e) {
            }
            @Override
            public void keyReleased(KeyEvent e) {  
            }
        });
        
    }
    private boolean checkEmail(){
        String email = jTFemail.getText();
        if(email.contains("@") && email.contains(".")){
            if(email.charAt(0)=='@'){
                JOptionPane.showMessageDialog(null, "Podano nie poprawny adres EMAIL!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                return false;
            }else{
                String host[] = email.split("@");
                if(host[1].charAt(0)=='.'){
                    JOptionPane.showMessageDialog(null, "Podano nie poprawny adres EMAIL!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                String dot = host[1];
                String dot2[] = dot.split("\\.");
                if(dot2[1].isEmpty()==true){
                    JOptionPane.showMessageDialog(null, "Podano nie poprawny adres EMAIL!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Podano nie poprawny adres EMAIL!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private void checkDate(){
    
        Date date = new Date();  
        System.out.println(date);
        String date2 = ""+jDCdate.getDate();
        System.out.println(date2);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jldate;
    private javax.swing.JButton jBsave;
    private com.toedter.calendar.JDateChooser jDCdate;
    private javax.swing.JLabel jLemail;
    private javax.swing.JLabel jLform;
    private javax.swing.JLabel jLheight;
    private javax.swing.JLabel jLlogin;
    private javax.swing.JLabel jLweight;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFheight;
    private javax.swing.JTextField jTFlogin;
    private javax.swing.JTextField jTFweight;
    // End of variables declaration//GEN-END:variables
}
